name: Train MNIST model

on:
  push:
  pull_request:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tensorflow matplotlib

      - name: Run training script
        run: python app/main.py

      - name: Upload training results
        uses: actions/upload-artifact@v4
        with:
          name: training-results
          path: app/output.png

      - name: Save training artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: |
            models/model.h5
            app/output.png
        
        
