name: Compile thesis
on:
  push:
    paths:
      - 'docs/latex/**'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install LaTeX packages
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-extra texlive-lang-european texlive-science ghostscript

    - name: Compile the thesis
      run: |
        cd $GITHUB_WORKSPACE/docs/latex/docs
        pdflatex main.tex
        bibtex main
        pdflatex main.tex
        pdflatex main.tex

    - name: Compress pdf
      run: |
        cd $GITHUB_WORKSPACE/docs/latex/docs
        ghostscript -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH \
        -sOutputFile=Template_thesis_compressed.pdf main.pdf

    - name: Commit and push PDF
      run: |
        git config user.email ${{ secrets.EMAIL }}
        git config user.name ${{ secrets.FULL_NAME }}
        cd $GITHUB_WORKSPACE/docs/latex/docs
        git add main.pdf Template_thesis_compressed.pdf
        git diff --cached --quiet || git commit -m "ci: update compiled thesis PDF [skip ci]"
        git push